Eager 925
variant-inc/terraform-aws-s3 pull request #10
Opened 2022-02-22 06:30 UTC by zumic96

# Description

This is new functionality with S3 which helps reduce number of steps that we need to set up in order to trigger some workflow based on S3 events.
DataOps team expects to utilize it often so it would make things much simpler to have it in module instead of defining resource each time we would want to enable this.

Fixes [#925](https://drivevariant.atlassian.net/browse/EAGER-925)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

```text
Local apply with variable `enable_bucket_notification` set to true and false to verify it enables EventBridge notification when set to true and does not create this extra resource if set to false.
Added variable in complex example.
```

- [ ] Sanity Testing

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added documentation to test

2022-02-22 11:23 UTC, vibindaniel approved these changes

2022-02-22 11:24 UTC, vibindaniel requested changes

2022-02-22 11:24 UTC, vibindaniel commented on README.md
>  | Name | Type |
Squash all commits

2022-02-22 11:38 UTC, zumic96 commented on README.md
>  | Name | Type |
Should I do it just when merging PR or did you mean to squash them in PR?
Also, a quick question regarding versioning/tagging of module, how is it handled, does your team add it or should I add it once PR is merged?

2022-03-09 19:47 UTC, jahnavimaddi reviewed
Tested locally, the notification resource is getting created only when the "enable_bucket_notification" is set to true. please resolve the above comments.

2022-03-10 11:25 UTC, zumic96 commented on README.md
>  | Name | Type |
squashed commits

2022-03-10 14:01 UTC, vibindaniel approved these changes

2022-03-10 14:01 UTC, merged