support for creating EB rule, default SNS topic and other event targets
variant-inc/terraform-aws-s3 pull request #11
Opened 2022-04-04 11:23 UTC by zumic96

# Description

Adds support for creating default EB rule that gets triggered by file drop in S3.
Optionally can create SNS topic with same name as bucket that gets matched event on file drop in S3.
Can also include other target's for the rule, lambda or SFN...anything supported by Event Bridge rules.

Fixes [#1021](https://drivevariant.atlassian.net/browse/EAGER-1021)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manual tests wit different options `enable_bucket_notification = true`.
`enable_sns_delivery = true` - creates SNS topic and EB rule that has it set as target
`enable_sns_delivery = false` - doesn't create SNS topic
`event targets = {<target config>}` = creates EB rule with specified target (creates SNS topic only if `enable_sns_delivery` is true)

- [ ] Sanity Testing

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added documentation to test

2022-04-04 11:58 UTC, vibindaniel commented on main.tf
> +  kms_master_key_id = "alias/aws/sns"
This key cannot be shared between accounts and hence a new key has to be created that has the ability to shared between accounts.

2022-04-05 07:59 UTC, zumic96 commented on main.tf
> +module "eb_rule" {
added an example for SQS
[example](https://github.com/variant-inc/terraform-aws-s3/pull/11/files#diff-a1abad2da4f74766841d88a2acfcdf090876bcec52b4e9cf1b8779443a6fb30fR12-R14)

2022-04-06 13:32 UTC, vibindaniel commented on examples/event_notification/main.tf
> +      arn = "arn:aws:sqs:us-east-1:123456789012:sqs"
Every time a project needs access to the eb through sqs, do they have to request out to you?

2022-04-06 13:43 UTC, vibindaniel commented on main.tf
> +  kms_master_key_id = "alias/aws/sns"
Was this tested anywhere?

2022-04-06 14:56 UTC, zumic96 commented on main.tf
> +  kms_master_key_id = "alias/aws/sns"
Initially I tested creating SNS topic but not the full flow
As I had test setup for cross account EB buses, I've added SNS target and it indeed didn't work with AWS managed CMK, had to create new one and set specific policies for it.
I'll add creation of it and setting minimal policies with option to add custom ones for cross-account access.

2022-04-07 10:07 UTC, zumic96 commented
Updated and tested on data-dev account, didn't delete for checkup purposes
Resources:
[S3](https://s3.console.aws.amazon.com/s3/buckets/test-luka-20220407090348255300000001?region=us-east-1&tab=objects)
[EB rule](https://us-east-1.console.aws.amazon.com/events/home?region=us-east-1#/eventbus/default/rules/test-luka--eb-rule)
[IAM Role](https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/roles/details/EventBridge-rule-test-luka--eb-rule?section=permissions)
[SNS Topic](https://us-east-1.console.aws.amazon.com/sns/v3/home?region=us-east-1#/topic/arn:aws:sns:us-east-1:854762601885:test-luka-20220407090348255300000001)
[KMS Key](https://us-east-1.console.aws.amazon.com/kms/home?region=us-east-1#/kms/keys/d8278083-8768-467f-a483-9da00ebfed44)
[SQS Queue](https://us-east-1.console.aws.amazon.com/sqs/v2/home?region=us-east-1#/queues/https%3A%2F%2Fsqs.us-east-1.amazonaws.com%2F854762601885%2Fluka-delete-0405)
Subscription to SNS was done manually, as I guess this will vary depending on the use case.

2022-04-07 13:10 UTC, vibindaniel commented on main.tf
> +        "arn:aws:iam::854762601885:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AWSAdministratorAccess_d03a558f68b16416"
Why is this hardcoded?

2022-04-07 13:13 UTC, vibindaniel requested changes

2022-04-07 13:13 UTC, vibindaniel commented on main.tf
> +resource "aws_sns_topic" "sns" {
SNS & KMS should be in its own module. This is adding lots of scope into the s3 module, which is for creating s3 buckets.

2022-04-07 14:00 UTC, zumic96 commented on main.tf
> +resource "aws_sns_topic" "sns" {
I agree, do you think we should still use those modules inside s3 module and that way hide this configuration from end user, similarly as it's being done with EB rule or just do it in final code where we'll also use s3 module?
What would be more in accordance with internal code practices?

2022-04-12 10:34 UTC, zumic96 commented on main.tf
> +resource "aws_sns_topic" "sns" {
@vibindaniel let me know which approach is preferred

2022-04-14 09:36 UTC, zumic96 commented
@vibindaniel I removed all other stuff and just made bucket event notifications to EventBridge bus as default.

Wasn't sure about the bucket policies so didn't touch those, should I make data account (648462982672) default for all buckets or should we add some kind of input? Especially if we'll want some access from data-dev in future or some other account.

2022-04-14 13:59 UTC, vibindaniel commented
> @vibindaniel I removed all other stuff and just made bucket event notifications to EventBridge bus as default.
> 
> Wasn't sure about the bucket policies so didn't touch those, should I make data account (648462982672) default for all buckets or should we add some kind of input? Especially if we'll want some access from data-dev in future or some other account.

The target account needs to be an input variable.

2022-04-14 14:06 UTC, vibindaniel commented
@zumic96 Can we have a call again tomorrow at the same time as yesterday?

2022-04-14 14:12 UTC, zumic96 commented
> @zumic96 Can we have a call again tomorrow at the same time as yesterday?

Sure thing.

2022-04-27 13:38 UTC, naveen-variant commented on .pre-commit-config.yaml
>      rev: v1.51.0
Can we also change this to latest version v1.68.1

2022-04-27 13:45 UTC, vibindaniel approved these changes

2022-04-27 14:12 UTC, zumic96 commented on .pre-commit-config.yaml
>      rev: v1.51.0
updated to latest version, could you please reapprove?

2022-04-27 15:07 UTC, jahnavimaddi reviewed
Created a test bucket by using this module in dpl and verified read-only access for the external accounts mentioned and the event bucket notification is enabled. Please refer below screenshots.

Please squash the commits before merge and address all the unresolved threads.
<img width="605" alt="Screen Shot 2022-04-27 at 10 54 57 AM" src="https://user-images.githubusercontent.com/97197935/165549701-1c3690f1-4c40-4b02-893c-12cd944aabbd.png">
<img width="562" alt="Screen Shot 2022-04-27 at 11 00 11 AM" src="https://user-images.githubusercontent.com/97197935/165549728-8758c0d5-0304-40d0-8501-2c186b7f8b52.png">

2022-04-27 16:20 UTC, naveen-variant commented
Created bucket, i see event bridge is enabled and read only access is enabled for external account.

2022-04-27 16:21 UTC, naveen-variant approved these changes

2022-04-28 14:04 UTC, jahnavimaddi approved these changes

2022-04-28 17:15 UTC, merged