Eager 760
variant-inc/terraform-aws-s3 pull request #4
Opened 2021-11-12 13:57 UTC by zumic96

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes [#8](https://usxtech.atlassian.net/browse/CLOUD-8)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

```text
Ran multiple tests to verify each feature works as expected.
All tests were run locally on laptop on Variant-Playground account.
```

- [ ] Sanity Testing

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added documentation to test

2021-11-12 13:58 UTC, vibindaniel commented on main.tf
> +  dynamic "replication_configuration" {
remove this pls

2021-11-12 14:02 UTC, vibindaniel requested changes

2021-11-12 14:02 UTC, vibindaniel commented on main.tf
>  resource "aws_s3_bucket_public_access_block" "bucket" {
revert this pls

2021-11-12 14:02 UTC, vibindaniel commented on main.tf
> +resource "aws_s3_bucket_object" "object_staging" {
remove everything from here to end of the file

2021-11-18 10:10 UTC, zumic96 commented on main.tf
> +  dynamic "replication_configuration" {
removed

2021-11-18 10:10 UTC, zumic96 commented on main.tf
> -  lifecycle {
reverted

2021-11-18 10:11 UTC, zumic96 commented on main.tf
> +  acl           = var.acl
reverted

2021-11-18 10:11 UTC, zumic96 commented on main.tf
>    versioning {
reverted

2021-11-18 10:11 UTC, zumic96 commented on main.tf
>        apply_server_side_encryption_by_default {
reverted

2021-11-18 10:11 UTC, zumic96 commented on main.tf
>  resource "aws_s3_bucket_public_access_block" "bucket" {
reverted

2021-11-18 10:11 UTC, zumic96 commented on main.tf
> +resource "aws_s3_bucket_object" "object_staging" {
removed

2021-11-22 14:03 UTC, vibindaniel submitted a review, later dismissed

2021-11-22 14:51 UTC, zumic96 commented
will make new PR with signed commits, sry for spam

2021-11-22 14:51 UTC, closed without merging